name: esrgan_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - pillow
  - tensorboard
  - scipy
  - opencv
  - pandas
  - yacs
  - pip
  - pip:
    - torch
    - torchvision
    - albumentations
    - tqdm